/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import PopUps.PopUps;
import controladores.Filme;

/**
 *
 * @author 104869
 */
public class FormCadastroFilm extends javax.swing.JFrame {

    static void start() {
        java.awt.EventQueue.invokeLater(() -> {
            new FormCadastroFilm().setVisible(true);
        });
    }

    /**
     * Creates new form FormCadsatroFilm
     */
    public FormCadastroFilm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        labelNome = new javax.swing.JLabel();
        labelMenorIdade = new javax.swing.JLabel();
        labelDuracao = new javax.swing.JLabel();
        labelGenero = new javax.swing.JLabel();
        botaoConfirmar = new javax.swing.JButton();
        textNome = new javax.swing.JTextField();
        textDuracao = new javax.swing.JFormattedTextField();
        checkAcao = new javax.swing.JCheckBox();
        checkAnimacao = new javax.swing.JCheckBox();
        checkAventura = new javax.swing.JCheckBox();
        checkComedia = new javax.swing.JCheckBox();
        opcaoLivre = new javax.swing.JRadioButton();
        opcao10 = new javax.swing.JRadioButton();
        opcao12 = new javax.swing.JRadioButton();
        opcao14 = new javax.swing.JRadioButton();
        opcao16 = new javax.swing.JRadioButton();
        opcao18 = new javax.swing.JRadioButton();
        checkDocumentario = new javax.swing.JCheckBox();
        checkFantasia = new javax.swing.JCheckBox();
        checkFaroeste = new javax.swing.JCheckBox();
        checkFiccao = new javax.swing.JCheckBox();
        checkGuerra = new javax.swing.JCheckBox();
        checkMusicais = new javax.swing.JCheckBox();
        checkRomance = new javax.swing.JCheckBox();
        checkSuspense = new javax.swing.JCheckBox();
        checkTerror = new javax.swing.JCheckBox();
        checkTragedia = new javax.swing.JCheckBox();
        botaoCancelar = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar Filme");
        setResizable(false);

        labelNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNome.setText("Nome do filme:");

        labelMenorIdade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMenorIdade.setText("Classificação indicativa:");

        labelDuracao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDuracao.setText("Duração:");

        labelGenero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGenero.setText("Gênero:");

        botaoConfirmar.setText("Confirmar");
        botaoConfirmar.setNextFocusableComponent(botaoCancelar);
        botaoConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConfirmarActionPerformed(evt);
            }
        });

        textNome.setToolTipText("Digite o nome do filme.");
        textNome.setNextFocusableComponent(opcaoLivre);

        try {
            textDuracao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        textDuracao.setToolTipText("Apenas números. 00:00 até 23:59.");
        textDuracao.setNextFocusableComponent(checkAcao);

        checkAcao.setText("Ação");
        checkAcao.setNextFocusableComponent(checkAnimacao);

        checkAnimacao.setText("Animação");
        checkAnimacao.setNextFocusableComponent(checkAventura);
        checkAnimacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAnimacaoActionPerformed(evt);
            }
        });

        checkAventura.setText("Aventura");
        checkAventura.setNextFocusableComponent(checkComedia);

        checkComedia.setText("Comédia");
        checkComedia.setNextFocusableComponent(checkDocumentario);

        buttonGroup1.add(opcaoLivre);
        opcaoLivre.setText("Livre");
        opcaoLivre.setNextFocusableComponent(opcao10);

        buttonGroup1.add(opcao10);
        opcao10.setText("10");
        opcao10.setNextFocusableComponent(opcao12);

        buttonGroup1.add(opcao12);
        opcao12.setText("12");
        opcao12.setNextFocusableComponent(opcao14);

        buttonGroup1.add(opcao14);
        opcao14.setText("14");
        opcao14.setNextFocusableComponent(opcao16);

        buttonGroup1.add(opcao16);
        opcao16.setText("16");
        opcao16.setNextFocusableComponent(opcao18);

        buttonGroup1.add(opcao18);
        opcao18.setText("18");
        opcao18.setNextFocusableComponent(textDuracao);

        checkDocumentario.setText("Documentário");
        checkDocumentario.setNextFocusableComponent(checkFantasia);

        checkFantasia.setText("Fantasia");
        checkFantasia.setNextFocusableComponent(checkFaroeste);

        checkFaroeste.setText("Faroeste");
        checkFaroeste.setNextFocusableComponent(checkGuerra);

        checkFiccao.setText("Ficção Científica");
        checkFiccao.setNextFocusableComponent(checkGuerra);

        checkGuerra.setText("Guerra");
        checkGuerra.setNextFocusableComponent(checkMusicais);

        checkMusicais.setText("Musicais");
        checkMusicais.setNextFocusableComponent(checkRomance);
        checkMusicais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMusicaisActionPerformed(evt);
            }
        });

        checkRomance.setText("Romance");
        checkRomance.setNextFocusableComponent(checkSuspense);

        checkSuspense.setText("Suspense");
        checkSuspense.setNextFocusableComponent(checkTerror);

        checkTerror.setText("Terror");
        checkTerror.setName(""); // NOI18N
        checkTerror.setNextFocusableComponent(checkTragedia);

        checkTragedia.setText("Tragédia");
        checkTragedia.setNextFocusableComponent(botaoConfirmar);

        botaoCancelar.setText("Cancelar");
        botaoCancelar.setNextFocusableComponent(textNome);
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(289, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botaoConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelDuracao)
                        .addComponent(labelGenero)
                        .addComponent(labelNome)
                        .addComponent(labelMenorIdade)))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkAventura)
                    .addComponent(checkComedia)
                    .addComponent(checkDocumentario)
                    .addComponent(checkFantasia)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkAcao)
                            .addComponent(checkAnimacao)
                            .addComponent(checkFaroeste))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkTragedia)
                            .addComponent(checkGuerra)
                            .addComponent(checkFiccao)
                            .addComponent(checkMusicais)
                            .addComponent(checkRomance)
                            .addComponent(checkSuspense)
                            .addComponent(checkTerror)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(botaoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(opcaoLivre)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(opcao10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(opcao12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(opcao14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(opcao16)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(opcao18))))
                .addContainerGap(300, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMenorIdade)
                    .addComponent(opcaoLivre)
                    .addComponent(opcao10)
                    .addComponent(opcao12)
                    .addComponent(opcao14)
                    .addComponent(opcao16)
                    .addComponent(opcao18))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDuracao)
                    .addComponent(textDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelGenero)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkAcao)
                            .addComponent(checkFiccao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkAnimacao)
                            .addComponent(checkGuerra))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkAventura)
                            .addComponent(checkMusicais))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkComedia)
                            .addComponent(checkRomance))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkDocumentario)
                            .addComponent(checkSuspense))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkFantasia)
                            .addComponent(checkTerror))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkFaroeste)
                            .addComponent(checkTragedia))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(119, 119, 119))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void checkAnimacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAnimacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkAnimacaoActionPerformed

    private void checkMusicaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMusicaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkMusicaisActionPerformed

    private void botaoConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConfirmarActionPerformed
        String genero = "";
        String classificacao = "";
        boolean invalido = false;
        if (textNome.getText().isEmpty()) {
            textNome.requestFocus();
            PopUps.displayErrorMessageJOP("Nome inválido!", this);
            invalido = true;
            return;
        }
        if ((!opcaoLivre.isSelected()) && (!opcao10.isSelected()) && (!opcao12.isSelected()) && (!opcao14.isSelected()) && (!opcao16.isSelected()) && (!opcao18.isSelected())) {
            opcaoLivre.requestFocus();
            PopUps.displayErrorMessageJOP("Selecione uma opção!", this);
            invalido = true;
            return;
        }
        if (textDuracao.getText().equals("  :  ")) {
            textDuracao.requestFocus();
            PopUps.displayErrorMessageJOP("Duração inválida!", this);
            invalido = true;
            return;
        }
        try {
            if ((Integer.parseInt(textDuracao.getText().substring(0, 2)) > 23) || (Integer.parseInt(textDuracao.getText().substring(3)) > 59)) {
                textDuracao.requestFocus();
                PopUps.displayErrorMessageJOP("Duração inválida", this);
                invalido = true;
                return;
            }
        } catch (Exception ex) {
            textDuracao.requestFocus();
            PopUps.displayErrorMessageJOP("Duração inválida", this);
            invalido = true;
            return;
        }
        if ((!checkAcao.isSelected()) && (!checkAnimacao.isSelected()) && (!checkAventura.isSelected()) && (!checkComedia.isSelected()) && (!checkDocumentario.isSelected()) && (!checkFantasia.isSelected()) && (!checkFaroeste.isSelected()) && (!checkFiccao.isSelected()) && (!checkGuerra.isSelected()) && (!checkMusicais.isSelected()) && (!checkRomance.isSelected()) && (!checkSuspense.isSelected()) && (!checkTerror.isSelected()) && (!checkTragedia.isSelected())) {
            checkAcao.requestFocus();
            PopUps.displayErrorMessageJOP("Selecione uma opção!", this);
            invalido = true;
            return;
        }

        if (opcaoLivre.isSelected()) {
            classificacao = "Livre";
        }
        if (opcao10.isSelected()) {
            classificacao = "10";
        }
        if (opcao12.isSelected()) {
            classificacao = "12";
        }
        if (opcao14.isSelected()) {
            classificacao = "14";
        }
        if (opcao16.isSelected()) {
            classificacao = "16";
        }
        if (opcao18.isSelected()) {
            classificacao = "18";
        }
        if (checkAcao.isSelected()) {
            genero = " Ação ";
        }
        if (checkAnimacao.isSelected()) {
            genero += " Animação ";
        }
        if (checkAventura.isSelected()) {
            genero += " Aventura ";
        }
        if (checkComedia.isSelected()) {
            genero += " Comédia ";
        }
        if (checkDocumentario.isSelected()) {
            genero += " Documentário ";
        }
        if (checkFantasia.isSelected()) {
            genero += " Fantasia ";
        }
        if (checkFaroeste.isSelected()) {
            genero += " Faroeste ";
        }
        if (checkFiccao.isSelected()) {
            genero += " Ficção ";
        }
        if (checkGuerra.isSelected()) {
            genero += " Guerra ";
        }
        if (checkMusicais.isSelected()) {
            genero += " Musicais ";
        }
        if (checkRomance.isSelected()) {
            genero += " Romance ";
        }
        if (checkSuspense.isSelected()) {
            genero += " Suspense ";
        }
        if (checkTerror.isSelected()) {
            genero += " Terror ";
        }
        if (checkTragedia.isSelected()) {
            genero += " Tragédia";
        }
        Filme f = new Filme(textNome.getText(), classificacao, genero, textDuracao.getText());
        for (int i = 0; i < f.getFilmes().size(); i++) {
            if (textNome.getText().equals(f.getFilmes().get(i).getNome())) {
                textNome.requestFocus();
                PopUps.displayErrorMessageJOP("Filme já cadastrado!", this);
                invalido = true;
                return;
            }
        }
        if (invalido == false) {
            f.getFilmes().add(f);
            PopUps.displaySuccessJOP("Filme cadastrado com sucesso!", this);
            System.out.println(f.getFilmes().size());
            textNome.setText("");
            textDuracao.setText("");
            opcaoLivre.setSelected(false);
            opcao10.setSelected(false);
            opcao12.setSelected(false);
            opcao14.setSelected(false);
            opcao16.setSelected(false);
            opcao18.setSelected(false);
            checkAcao.setSelected(false);
            checkAnimacao.setSelected(false);
            checkAventura.setSelected(false);
            checkComedia.setSelected(false);
            checkDocumentario.setSelected(false);
            checkFantasia.setSelected(false);
            checkFaroeste.setSelected(false);
            checkFiccao.setSelected(false);
            checkGuerra.setSelected(false);
            checkMusicais.setSelected(false);
            checkRomance.setSelected(false);
            checkSuspense.setSelected(false);
            checkTerror.setSelected(false);
            checkTragedia.setSelected(false);
            textNome.requestFocus();
        }
    }//GEN-LAST:event_botaoConfirmarActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        this.dispose();
        FormOptionGerente.start();
    }//GEN-LAST:event_botaoCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCadastroFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCadastroFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCadastroFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCadastroFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCadastroFilm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoConfirmar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JCheckBox checkAcao;
    private javax.swing.JCheckBox checkAnimacao;
    private javax.swing.JCheckBox checkAventura;
    private javax.swing.JCheckBox checkComedia;
    private javax.swing.JCheckBox checkDocumentario;
    private javax.swing.JCheckBox checkFantasia;
    private javax.swing.JCheckBox checkFaroeste;
    private javax.swing.JCheckBox checkFiccao;
    private javax.swing.JCheckBox checkGuerra;
    private javax.swing.JCheckBox checkMusicais;
    private javax.swing.JCheckBox checkRomance;
    private javax.swing.JCheckBox checkSuspense;
    private javax.swing.JCheckBox checkTerror;
    private javax.swing.JCheckBox checkTragedia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelDuracao;
    private javax.swing.JLabel labelGenero;
    private javax.swing.JLabel labelMenorIdade;
    private javax.swing.JLabel labelNome;
    private javax.swing.JRadioButton opcao10;
    private javax.swing.JRadioButton opcao12;
    private javax.swing.JRadioButton opcao14;
    private javax.swing.JRadioButton opcao16;
    private javax.swing.JRadioButton opcao18;
    private javax.swing.JRadioButton opcaoLivre;
    private javax.swing.JFormattedTextField textDuracao;
    private javax.swing.JTextField textNome;
    // End of variables declaration//GEN-END:variables
}
