/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import PopUps.PopUps;
import controladores.Sala;

/**
 *
 * @author T-Gamer
 */
public class FormVendedor extends javax.swing.JFrame {

    static void start() {
        java.awt.EventQueue.invokeLater(() -> {
            new FormVendedor().setVisible(true);
        });
    }

    /**
     * Creates new form FormVendedor
     */
    public FormVendedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoVenderIngresso = new javax.swing.JButton();
        botaoEsvaziarSala = new javax.swing.JButton();
        botaoLogoff = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        botaoVenderIngresso.setText("Vender Ingresso");
        botaoVenderIngresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVenderIngressoActionPerformed(evt);
            }
        });

        botaoEsvaziarSala.setText("Esvaziar Sala");
        botaoEsvaziarSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEsvaziarSalaActionPerformed(evt);
            }
        });

        botaoLogoff.setText("Logoff");
        botaoLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLogoffActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(botaoVenderIngresso)
                        .addGap(69, 69, 69)
                        .addComponent(botaoEsvaziarSala))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(botaoLogoff)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoVenderIngresso)
                    .addComponent(botaoEsvaziarSala))
                .addGap(73, 73, 73)
                .addComponent(botaoLogoff)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVenderIngressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVenderIngressoActionPerformed
        Sala s = new Sala();
        if (s.getSalas().isEmpty()) {
            PopUps.displayErrorMessageJOP("Você precisa ter ao menos uma sala cadastrada para usar essa função!", this);
        } else {
            this.dispose();
            FormVendedorIngresso.start();
        }
    }//GEN-LAST:event_botaoVenderIngressoActionPerformed

    private void botaoEsvaziarSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEsvaziarSalaActionPerformed
        Sala s = new Sala();
        if (s.getSalas().isEmpty()) {
            PopUps.displayErrorMessageJOP("Você precisa ter ao menos uma sala cadastrada para usar essa função!", this);
        } else {
            this.dispose();
            FormEsvaziarSalaVendedor.start();
        }
    }//GEN-LAST:event_botaoEsvaziarSalaActionPerformed

    private void botaoLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLogoffActionPerformed
        this.dispose();
        FormLogin fl = new FormLogin();
        fl.setVisible(true);
    }//GEN-LAST:event_botaoLogoffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormVendedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEsvaziarSala;
    private javax.swing.JButton botaoLogoff;
    private javax.swing.JButton botaoVenderIngresso;
    // End of variables declaration//GEN-END:variables
}
